export const STAT_DEFINITIONS: Record<string, string> = {
  // Football
  'RUSH YDS': 'Total rushing yards',
  'CARRIES': 'Number of rushing attempts',
  'RUSH TD': 'Rushing touchdowns scored',
  'YPC': 'Yards per carry (rushing yards / carries)',
  'PASS YDS': 'Total passing yards',
  'COMP': 'Pass completions',
  'ATT': 'Pass attempts',
  'TD': 'Touchdowns',
  'INT': 'Interceptions thrown',
  'QBR': 'Quarterback rating',
  'REC': 'Receptions (catches)',
  'REC YDS': 'Receiving yards',
  'REC TD': 'Receiving touchdowns',
  'YPR': 'Yards per reception',
  'PTS': 'Total points scored',
  // Basketball
  'PPG': 'Points per game',
  'RPG': 'Rebounds per game',
  'APG': 'Assists per game',
  'GP': 'Games played',
  'FG%': 'Field goal percentage',
  'FT%': 'Free throw percentage',
  '3PT%': 'Three-point field goal percentage',
  'STL': 'Steals per game',
  'BLK': 'Blocks per game',
  // Baseball
  'AVG': 'Batting average',
  'HR': 'Home runs',
  'RBI': 'Runs batted in',
  'ERA': 'Earned run average',
  'K': 'Strikeouts',
  'W': 'Wins',
  'L': 'Losses',
  'T': 'Ties',
  'W-L': 'Win-Loss record',
  'WIN%': 'Winning percentage',
  // General
  'GS': 'Games started',
  'SEASON': 'School year / season',
};
