import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Recruiting | Philadelphia High School Sports',
    description: 'Recruiting hub for Philadelphia high school athletes.',
    };

    export default function RecruitingPage() {
      return (
          <main style={{ padding: '2rem', maxWidth: '960px', margin: '0 auto' }}>
                <section style={{ background: 'var(--psp-navy)', borderRadius: '12px', padding: '2.5rem', marginBottom: '2.5rem', color: '#fff' }}>
                        <h1 style={{ fontFamily: 'var(--font-bebas)', fontSize: '2.75rem', margin: '0 0 0.5rem' }}>
                                  Recruiting Hub
                                          </h1>
                                                  <p style={{ color: 'rgba(255,255,255,0.75)', maxWidth: '560px', marginBottom: '1.5rem' }}>
                                                            The definitive source for Philadelphia high school recruiting.
                                                                    </p>
                                                                            <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
                                                                                      <Link href="/players" style={{ background: 'var(--psp-gold)', color: 'var(--psp-navy)', padding: '0.65rem 1.5rem', borderRadius: '6px', textDecoration: 'none', fontWeight: 700, fontFamily: 'var(--font-bebas)', fontSize: '1.1rem' }}>
                                                                                                  Browse Prospects
                                                                                                            </Link>
                                                                                                                      <a href="mailto:mwallace35@gmail.com?subject=Coach Inquiry" style={{ background: 'transparent', color: '#fff', padding: '0.65rem 1.5rem', borderRadius: '6px', textDecoration: 'none', fontWeight: 600, border: '2px solid rgba(255,255,255,0.4)' }}>
                                                                                                                                  Coach Inquiry
                                                                                                                                            </a>
                                                                                                                                                    </div>
                                                                                                                                                          </section>
                                                                                                                                                                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))', gap: '1rem', marginBottom: '2.5rem' }}>
                                                                                                                                                                        {[
                                                                                                                                                                                  { href: '/players', label: 'Find Prospects', desc: 'Search 10,000+ athletes by sport, school, and year' },
                                                                                                                                                                                            { href: '/leaderboards', label: 'Stat Leaders', desc: 'Top performers across every sport and season' },
                                                                                                                                                                                                      { href: '/leaderboards/trending', label: 'Trending', desc: 'Athletes gaining the most attention right now' },
                                                                                                                                                                                                                { href: '/standings', label: 'Team Records', desc: 'School performance and league standings' },
                                                                                                                                                                                                                        ].map((card) => (
                                                                                                                                                                                                                                  <Link key={card.href} href={card.href} style={{ display: 'block', background: 'var(--psp-card-bg)', border: '1px solid #e2e8f0', borderRadiiumsp:o r't8 ptxy'p,e  p{a dMdeitnagd:a t'a1 .}2 5frreomm' ,' nteexxtt'D;e
                                                                                                                                                                                                                                  ciomrpaotrito nL:i n'kn ofnreo'm,  'cnoelxotr/:l i'nikn'h;e
                                                                                                                                                                                                                                  r
                                                                                                                                                                                                                                  ietx'p o}r}t> 
                                                                                                                                                                                                                                  c o n s t   m e t a d a t<ad:i vM esttaydlaet=a{ {=  f{o
                                                                                                                                                                                                                                  n t Ftaimtilley::  ''Rveacrr(u-i-tfionngt -|b ePbhaisl)a'd,e lfpohnitaS iHzieg:h  'S1c.h1o5orle mS'p,o rctosl'o,r
                                                                                                                                                                                                                                  :   'dveasrc(r-i-pptsipo-nn:a v'yR)e'c,r umiatrignign Bhoutbt ofmo:r  'P0h.i2l5ardeeml'p h}i}a> {hciagrhd .slcahboeoll} <a/tdhilve>t
                                                                                                                                                                                                                                  e s . ' , 
                                                                                                                                                                                                                                   } ; 
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                     e x p<odritv  dsetfyaluel=t{ {f ufnocnttiSoinz eR:e c'r0u.i8t5irnegmP'a,g ec(o)l o{r
                                                                                                                                                                                                                                     :   'rveatru(r-n- p(s
                                                                                                                                                                                                                                     p - m u t<emda)i'n  }s}t>y{lcea=r{d{. dpeasdcd}i<n/gd:i v'>2
                                                                                                                                                                                                                                     r e m ' ,   m a x W i<d/tLhi:n k'>9
                                                                                                                                                                                                                                     6 0 p x ' ,   m a)r)g}i
                                                                                                                                                                                                                                     n :   ' 0   a<u/tdoi'v >}
                                                                                                                                                                                                                                     } > 
                                                                                                                                                                                                                                             < s e<csteicotni osnt ysltey=l{e{= {b{a cbkagcrkogurnodu:n d':v a'rv(a-r-(p-s-pp-scpa-rnda-vbyg))'',,  bboorrddeerrRRaaddiiuuss::  ''1120ppxx'',,  ppaaddddiinngg::  ''21..55rreemm'',,  mmaarrggiinnBBoottttoomm::  ''22.r5erme'm '},} >c
                                                                                                                                                                                                                                             o l o r :   ' # f<fhf2'  s}t}y>l
                                                                                                                                                                                                                                             e = { {   f o n t<Fha1m isltyy:l e'=v{a{r (f-o-nftoFnatm-ibleyb:a s')v'a,r (f-o-nftoSnitz-eb:e b'a1s.)5'r,e mf'o,n tcSoilzoer::  ''2v.a7r5(r-e-mp's,p -mnaarvgyi)n':,  'm0a r0g i0n.B5ortetmo'm :} }'>1
                                                                                                                                                                                                                                             r e m '   } } > 
                                                                                                                                                                                                                                                 R e c r u i t i nPgr oH uPbi
                                                                                                                                                                                                                                                 p e l i n e 
                                                                                                                                                                                                                                                     < / h 1 > 
                                                                                                                                                                                                                                                       < / h 2 > 
                                                                                                                                                                                                                                                           < p   s t y l<ed=i{v{  sctoylloer=:{ {' rdgibsap(l2a5y5:, 2'5f5l,e2x5'5,, 0g.a7p5:) '',2 rmeamx'W,i dftlhe:x W'r5a6p0:p x''w,r ampa'r g}i}n>B
                                                                                                                                                                                                                                                           o t t o m :   ' 1 . 5{r[e
                                                                                                                                                                                                                                                           m '   } } > 
                                                                                                                                                                                                                                                                       {   l a bTehle:  d'eNfFiLn iPtliavyee rsso'u,r cceo ufnotr:  P'h2i2l2a+d'e l}p,h
                                                                                                                                                                                                                                                                       i a   h i g h   s c h o o{l  lraebcerlu:i t'iNnBgA. 
                                                                                                                                                                                                                                                                       P l a y e r s ' ,< /cpo>u
                                                                                                                                                                                                                                                                       n t :   ' 8 7 + '< d}i,v
                                                                                                                                                                                                                                                                         s t y l e = { {   d i s{p llaayb:e l':f l'eMxL'B,  Pglaapy:e r's1'r,e mc'o,u nftl:e x'W1r1a6p+:'  '}w,r
                                                                                                                                                                                                                                                                         a p '   } } > 
                                                                                                                                                                                                                                                                               ] . m a p ( ( s<tLaitn)k  =h>r e(f
                                                                                                                                                                                                                                                                               = " / p l a y e r s "   s<tdyilve =k{e{y =b{asctkagtr.oluanbde:l }'>v
                                                                                                                                                                                                                                                                               a r ( - - p s p - g o l d ) '<,d icvo lsotry:l e'=v{a{r (f-o-nptsFpa-mnialvyy:) '',v apra(d-d-ifnogn:t -'b0e.b6a5sr)e'm,  1f.o5nrteSmi'z,e :b o'r2dreermR'a,d icuosl:o r':6 p'xv'a,r (t-e-xptsDpe-cgoorladt)i'o n}:} >'{nsotnaet'.,c ofuonntt}W<e/idgihvt>:
                                                                                                                                                                                                                                                                                 7 0 0 ,   f o n t F a m i l<yd:i v' vsatry(l-e-=f{o{n tf-obnetbSaisz)e':,  'f0o.n8t5Sriezme':,  'c1o.l1orre:m '' v}a}r>(
                                                                                                                                                                                                                                                                                 - - p s p - m u t e d ) 'B r}o}w>s{es tParto.slpaebcetls}
                                                                                                                                                                                                                                                                                 < / d i v > 
                                                                                                                                                                                                                                                                                         < / L i n k > 
                                                                                                                                                                                                                                                                                           < / d i v > 
                                                                                                                                                                                                                                                                                                 < a   h r e f =)")m}a
                                                                                                                                                                                                                                                                                                 i l t o : m w a l<l/adciev3>5
                                                                                                                                                                                                                                                                                                 @ g m a i l .<c/osme?cstuibojne>c
                                                                                                                                                                                                                                                                                                 t = C o a c h< sIencqtuiiorny "s tsytlyel=e{={{ {b abcakcgkrgoruonudn:d :' v'atrr(a-n-sppsapr-ennatv'y,) 'c,o lboorr:d e'r#Rfafdfi'u,s :p a'd1d0ipnxg':,  'p0a.d6d5irnegm:  1'.15.r5erme'm,' ,b ocrodleorrR:a d'i#ufsf:f '',6 ptxe'x,t AtleixgtnD:e c'ocreanttieorn':  }'}n>o
                                                                                                                                                                                                                                                                                                 n e ' ,   f o n t<Whe2i gshtty:l e6=0{0{,  fboonrtdFearm:i l'y2:p x' vsaorl(i-d- frognbta-(b2e5b5a,s2)5'5,, 2f5o5n,t0S.i4z)e':  }'}1>.
                                                                                                                                                                                                                                                                                                 5 r e m ' ,   m a r g i nC:o a'c0h  0I n0q.u5irreym
                                                                                                                                                                                                                                                                                                 '   } } > 
                                                                                                                                                                                                                                                                                                           < / a > 
                                                                                                                                                                                                                                                                                                             C o a c h e s :< /Gdeitv >E
                                                                                                                                                                                                                                                                                                             a r l y   A c<c/essesc
                                                                                                                                                                                                                                                                                                             t i o n > 
                                                                                                                                                                                                                                                                                                                   < / h 2<>d
                                                                                                                                                                                                                                                                                                                   i v   s t y l e =<{p{  sdtiyslpel=a{y{:  c'oglroird:' ,' rggrbiad(T2e5m5p,l2a5t5e,C2o5l5u,m0n.s7:) '',r empaeragti(naBuottot-ofmi:l l',1 rmeimn'm,a xf(o2n2t0Spixz,e :1 f'r0).)9'r,e mg'a p}:} >'
                                                                                                                                                                                                                                                                                                                   1 r e m ' ,   m a r gAidnvBaontcteodm :r e'c2r.u5irteimn'g  }t}o>o
                                                                                                                                                                                                                                                                                                                   l s   a n d   v e{r[i
                                                                                                                                                                                                                                                                                                                   f i e d   a t h l e t{e  hprreoff:i l'e/sp lcaoymeirnsg' ,s oloanb.e
                                                                                                                                                                                                                                                                                                                   l :   ' F i n d  <P/rpo>s
                                                                                                                                                                                                                                                                                                                   p e c t s ' ,   d<eas ch:r e'fS=e"amracihl t1o0:,m0w0a0l+l aacteh3l5e@tgemsa ibly. csopmo?rstu,b jsecchto=oClo,a cahn dE ayrelayr 'A c}c,e
                                                                                                                                                                                                                                                                                                                   s s "   s t y l e = {{{  hbraecfk:g r'o/ulneda:d e'rvbaora(r-d-sp's,p -lgaobledl):' ,' Sctoalto rL:e a'dvearrs('-,- pdseps-cn:a v'yT)o'p,  ppeardfdoirnmge:r s' 0a.c6rroesms  1e.v5erreym 's,p obrotr daenrdR asdeiausso:n '' 6}p,x
                                                                                                                                                                                                                                                                                                                   ' ,   t e x t D e c o{r ahtrieofn::  ''/nloenaed'e,r bfooanrtdWse/itgrhetn:d i7n0g0',,  floanbteFla:m i'lTyr:e n'dvianrg('-,- fdoenstc-:b e'bAatsh)l'e t}e}s> 
                                                                                                                                                                                                                                                                                                                   g a i n i n g   t h eR emqousets ta tAtcecnetsiso
                                                                                                                                                                                                                                                                                                                   n   r i g h t   n<o/wa'> 
                                                                                                                                                                                                                                                                                                                   } , 
                                                                                                                                                                                                                                                                                                                           < / s e c t i{o nh>r
                                                                                                                                                                                                                                                                                                                           e f :   '<//smtaainnd>i
                                                                                                                                                                                                                                                                                                                           n g s)';,
                                                                                                                                                                                                                                                                                                                            }label: 'Team Records', desc: 'School performance and league standings' },
                                                                                                                                                                                                                                                                                                                                    ].map((card) => (
                                                                                                                                                                                                                                                                                                                                              <Link key={card.href} href={card.href} style={{ display: 'block', background: 'var(--psp-card-bg)', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '1.25rem', textDecoration: 'none', color: 'inherit' }}>
                                                                                                                                                                                                                                                                                                                                                          <div style={{ fontFamily: 'var(--font-bebas)', fontSize: '1.15rem', color: 'var(--psp-navy)', marginBottom: '0.25rem' }}>{card.label}</div>
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '0.85rem', color: 'var(--psp-muted)' }}>{card.desc}</div>
                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                    <section style={{ background: 'var(--psp-card-bg)', borderRadius: '10px', padding: '1.5rem', marginBottom: '2rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                            <h2 style={{ fontFamily: 'var(--font-bebas)', fontSize: '1.5rem', color: 'var(--psp-navy)', marginBottom: '1rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                      Pro Pipeline
                                                                                                                                                                                                                                                                                                                                                                                                                              </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: '2rem', flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                            { label: 'NFL Players', count: '222+' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { label: 'NBA Players', count: '87+' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { label: 'MLB Players', count: '116+' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ].map((stat) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div key={stat.label}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ fontFamily: 'var(--font-bebas)', fontSize: '2rem', color: 'var(--psp-gold)' }}>{stat.count}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ fontSize: '0.85rem', color: 'var(--psp-muted)' }}>{stat.label}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <section style={{ background: 'var(--psp-navy)', borderRadius: '10px', padding: '1.5rem', color: '#fff', textAlign: 'center' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 style={{ fontFamily: 'var(--font-bebas)', fontSize: '1.5rem', margin: '0 0 0.5rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Coaches: Get Early Access
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ color: 'rgba(255,255,255,0.7)', marginBottom: '1rem', fontSize: '0.9rem' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Advanced recruiting tools and verified athlete profiles coming soon.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a href="mailto:mwallace35@gmail.com?subject=Coach Early Access" style={{ background: 'var(--psp-gold)', color: 'var(--psp-navy)', padding: '0.6rem 1.5rem', borderRadius: '6px', textDecoration: 'none', fontWeight: 700, fontFamily: 'var(--font-bebas)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Request Access
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
