-- Insert playoff brackets
BEGIN;

-- Bracket 1: 2026 Philadelphia Public League Boys Basketball Playoffs
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification) VALUES ('basketball', 76, '2026 Philadelphia Public League Boys Basketball Playoffs', 'public_league', NULL);

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Play-In', 1, 1, 'George Washington', 62, NULL, 'Overbrook', 79, NULL, '2026-02-05');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Play-In', 1, 2, 'Belmont Charter', 48, NULL, 'Sayre', 52, NULL, '2026-02-05');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Play-In', 1, 3, 'TECH Freire Charter', 57, NULL, 'Science Leadership Academy', 31, NULL, '2026-02-05');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Play-In', 1, 4, 'Parkway Northwest', 35, NULL, 'Hill Freedman World Academy', 42, NULL, '2026-02-05');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Play-In', 1, 5, 'Benjamin Franklin', 64, NULL, 'Jules E. Mastbaum Vo-Tech', 43, NULL, '2026-02-05');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Play-In', 1, 6, 'MAST Charter II', 69, NULL, 'Tacony Academy Charter', 64, NULL, '2026-02-05');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 1, 'Samuel Fels', 91, NULL, 'Overbrook', 50, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 2, 'Mastery Charter North - Pickett', 31, NULL, 'Martin Luther King', 33, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 3, 'High School of the Future', 68, NULL, 'MaST Community Charter School III', 59, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 4, 'Murrell Dobbins Vo-Tech', 81, NULL, 'Vaux Big Picture', 48, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 5, 'Sankofa Freedom Academy', 57, NULL, 'Sayre', 31, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 6, 'Abraham Lincoln', 62, NULL, 'Thomas A. Edison', 58, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 7, 'Franklin Towne', 58, NULL, 'Frankford', 59, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 8, 'West Philadelphia', 76, NULL, 'TECH Freire Charter', 44, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 9, 'Imhotep Charter', 68, NULL, 'Hill Freedman World Academy', 14, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 10, 'Kensington', 48, NULL, 'Simon Gratz', 51, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 11, 'Audenried', 71, NULL, 'Freire Charter', 44, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 12, 'Paul Robeson', 78, NULL, 'Mastery Charter South co-op', 43, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 13, 'Carver High School of Engineering & Science', 72, NULL, 'Benjamin Franklin', 31, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 14, 'Roxborough', 46, NULL, 'Science Leadership Academy at Beeber', 44, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 15, 'Olney', 56, NULL, 'Northeast', 42, NULL, '2026-02-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 1', 2, 16, 'Constitution', 80, NULL, 'MAST Charter II', 40, NULL, '2026-02-06');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 1, 'Samuel Fels', 71, NULL, 'Martin Luther King', 47, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 2, 'High School of the Future', 49, NULL, 'Murrell Dobbins Vo-Tech', 62, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 3, 'Sankofa Freedom Academy', 57, NULL, 'Abraham Lincoln', 42, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 4, 'Frankford', 55, NULL, 'West Philadelphia', 88, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 5, 'Imhotep Charter', 71, NULL, 'Simon Gratz', 35, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 6, 'Audenried', 51, NULL, 'Paul Robeson', 59, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 7, 'Carver High School of Engineering & Science', 79, NULL, 'Roxborough', 50, NULL, '2026-02-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Round 2', 3, 8, 'Olney', 67, NULL, 'Constitution', 86, NULL, '2026-02-10');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Quarter-Finals', 4, 1, 'Samuel Fels', 57, NULL, 'Murrell Dobbins Vo-Tech', 61, NULL, '2026-02-12');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Quarter-Finals', 4, 2, 'Sankofa Freedom Academy', 42, NULL, 'West Philadelphia', 48, NULL, '2026-02-12');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Quarter-Finals', 4, 3, 'Imhotep Charter', 71, NULL, 'Paul Robeson', 46, NULL, '2026-02-12');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Quarter-Finals', 4, 4, 'Carver High School of Engineering & Science', 0, NULL, 'Constitution', 2, NULL, '2026-02-12');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Semi-Finals', 5, 1, 'Murrell Dobbins Vo-Tech', 47, NULL, 'West Philadelphia', 68, NULL, '2026-02-17');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Semi-Finals', 5, 2, 'Imhotep Charter', 73, NULL, 'Constitution', 41, NULL, '2026-02-17');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='public_league' LIMIT 1), 'Championship', 6, 1, 'West Philadelphia', 35, NULL, 'Imhotep Charter', 39, NULL, '2026-02-22');

-- Bracket 2: 2026 PIAA Boys Basketball Championships - 6A
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification) VALUES ('basketball', 76, '2026 PIAA Boys Basketball Championships - 6A', 'piaa_6a', '6A');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 1, 'Plymouth Whitemarsh', 75, NULL, 'Cedar Cliff', 45, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 2, 'Liberty', 61, NULL, 'Wilkes-Barre', 52, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 3, 'Central York', 59, NULL, 'Cheltenham', 54, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 4, 'Father Judge', 61, NULL, 'Spring-Ford', 45, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 5, 'Imhotep Charter', 70, NULL, 'Garnet Valley', 40, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 6, 'William Penn', 80, NULL, 'Pocono Mountain East', 69, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 7, 'Delaware Valley', 56, NULL, 'Abington', 54, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 8, 'Parkland', 61, NULL, 'Conestoga', 47, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 9, 'Central Dauphin', 64, NULL, 'Pennsbury', 45, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 10, 'Souderton', 68, NULL, 'Archbishop Wood', 66, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 11, 'Methacton', 49, NULL, 'Whitehall', 46, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 12, 'New Castle', 68, NULL, 'Wilson', 38, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 13, 'Coatesville', 49, NULL, 'Chambersburg', 57, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 14, 'Taylor Allderdice', 34, NULL, 'Central Catholic', 48, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 15, 'Upper St. Clair', 66, NULL, 'Cedar Crest', 52, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'First Round', 1, 16, 'Red Lion', 69, NULL, 'Seneca Valley', 62, NULL, '2026-03-07');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 1, 'Plymouth Whitemarsh', 59, NULL, 'Liberty', 46, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 2, 'Central York', 68, NULL, 'Father Judge', 82, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 3, 'Imhotep Charter', 68, NULL, 'William Penn', 45, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 4, 'Delaware Valley', 33, NULL, 'Parkland', 62, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 5, 'Central Dauphin', 68, NULL, 'Souderton', 55, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 6, 'Methacton', 61, NULL, 'New Castle', 65, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 7, 'Chambersburg', 38, NULL, 'Central Catholic', 48, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Second Round', 2, 8, 'Upper St. Clair', 66, NULL, 'Red Lion', 69, NULL, '2026-03-11');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Quarterfinals', 3, 1, 'Plymouth Whitemarsh', 54, NULL, 'Father Judge', 58, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Quarterfinals', 3, 2, 'Imhotep Charter', 70, NULL, 'Parkland', 39, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Quarterfinals', 3, 3, 'Central Dauphin', 54, NULL, 'New Castle', 43, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Quarterfinals', 3, 4, 'Central Catholic', 46, NULL, 'Upper St. Clair', 52, NULL, '2026-03-14');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Semi-Finals', 4, 1, 'Father Judge', 48, NULL, 'Imhotep Charter', 51, NULL, '2026-03-17');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Semi-Finals', 4, 2, 'Central Dauphin', 55, NULL, 'Upper St. Clair', 52, NULL, '2026-03-17');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_6a' LIMIT 1), 'Finals', 5, 1, 'Imhotep Charter', 49, NULL, 'Central Dauphin', 52, NULL, '2026-03-21');

-- Bracket 3: 2026 PIAA Boys Basketball Championships - 5A
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification) VALUES ('basketball', 76, '2026 PIAA Boys Basketball Championships - 5A', 'piaa_5a', '5A');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 1, 'Upper Dublin', 57, NULL, 'Spring Grove', 43, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 2, 'Selinsgrove', 35, NULL, 'Monsignor Bonner/Archbishop Prendergast Catholic', 68, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 3, 'Abington Heights', 47, NULL, 'Springfield', 49, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 4, 'Frankford', 55, NULL, 'Octorara Area', 69, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 5, 'Southern Lehigh', 40, NULL, 'Upper Moreland', 61, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 6, 'Penncrest', 36, NULL, 'York Suburban', 29, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 7, 'Neumann-Goretti', 95, NULL, 'Pottstown', 60, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 8, 'Holy Ghost Prep', 58, NULL, 'Crestwood', 60, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 9, 'West York Area', 64, NULL, 'Ringgold', 57, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 10, 'Meadville', 45, NULL, 'Penn Hills', 58, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 11, 'Hershey', 49, NULL, 'Moon Area', 55, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 12, 'Thomas Jefferson', 66, NULL, 'New Oxford', 61, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 13, 'Chartiers Valley', 66, NULL, 'Exeter Township', 42, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 14, 'Hampton', 58, NULL, 'Cocalico', 61, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 15, 'Milton Hershey', 39, NULL, 'Gateway', 49, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'First Round', 1, 16, 'Greater Johnstown', 68, NULL, 'Shaler Area', 56, NULL, '2026-03-06');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 1, 'Upper Dublin', 58, NULL, 'Monsignor Bonner/Archbishop Prendergast Catholic', 67, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 2, 'Springfield', 54, NULL, 'Octorara Area', 28, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 3, 'Upper Moreland', 58, NULL, 'Penncrest', 53, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 4, 'Neumann-Goretti', 55, NULL, 'Crestwood', 24, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 5, 'West York Area', 56, NULL, 'Penn Hills', 42, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 6, 'Moon Area', 87, NULL, 'Thomas Jefferson', 77, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 7, 'Chartiers Valley', 64, NULL, 'Cocalico', 61, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Second Round', 2, 8, 'Gateway', 49, NULL, 'Greater Johnstown', 68, NULL, '2026-03-10');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Quarterfinals', 3, 1, 'Monsignor Bonner/Archbishop Prendergast Catholic', 61, NULL, 'Springfield', 52, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Quarterfinals', 3, 2, 'Upper Moreland', 62, NULL, 'Neumann-Goretti', 52, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Quarterfinals', 3, 3, 'West York Area', 59, NULL, 'Moon Area', 53, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Quarterfinals', 3, 4, 'Chartiers Valley', 42, NULL, 'Greater Johnstown', 36, NULL, '2026-03-13');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Semi-Finals', 4, 1, 'Monsignor Bonner/Archbishop Prendergast Catholic', 54, NULL, 'Upper Moreland', 28, NULL, '2026-03-16');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Semi-Finals', 4, 2, 'West York Area', 45, NULL, 'Chartiers Valley', 44, NULL, '2026-03-16');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_5a' LIMIT 1), 'Finals', 5, 1, 'Monsignor Bonner/Archbishop Prendergast Catholic', 62, NULL, 'West York Area', 35, NULL, '2026-03-20');

-- Bracket 4: 2026 PIAA Boys Basketball Championships - 4A
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification) VALUES ('basketball', 76, '2026 PIAA Boys Basketball Championships - 4A', 'piaa_4a', '4A');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 1, 'Archbishop Carroll', 77, NULL, 'Wyomissing', 52, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 2, 'Bishop McDevitt', 78, NULL, 'Mount Carmel', 34, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 3, 'Pope John Paul II', 59, NULL, 'Murrell Dobbins Vo-Tech', 28, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 4, 'Lewisburg', 70, NULL, 'Big Spring', 54, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 5, 'Allentown Central Catholic', 47, NULL, 'Devon Prep', 68, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 6, 'Montoursville', 44, NULL, 'Valley View', 58, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 7, 'West Philadelphia', 45, NULL, 'Salisbury Township', 54, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 8, 'Scranton Prep', 65, NULL, 'Schuylkill Valley', 48, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 9, 'Berks Catholic', 35, NULL, 'Carver High School of Engineering & Science', 40, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 10, 'Northwestern Lehigh', 48, NULL, 'Dallas', 57, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 11, 'Knoch', 46, NULL, 'Girard', 30, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 12, 'Sharon', 52, NULL, 'North Catholic', 64, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 13, 'Quaker Valley', 43, NULL, 'Hickory', 47, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 14, 'Huntingdon', 47, NULL, 'Deer Lakes', 64, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 15, 'Obama Academy of International Studies', 55, NULL, 'Warren', 50, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'First Round', 1, 16, 'Cathedral Prep', 79, NULL, 'Central Valley', 49, NULL, '2026-03-06');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 1, 'Archbishop Carroll', 36, NULL, 'Bishop McDevitt', 41, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 2, 'Pope John Paul II', 59, NULL, 'Lewisburg', 64, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 3, 'Devon Prep', 61, NULL, 'Valley View', 42, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 4, 'Salisbury Township', 57, NULL, 'Scranton Prep', 42, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 5, 'Carver High School of Engineering & Science', 69, NULL, 'Dallas', 53, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 6, 'Knoch', 69, NULL, 'North Catholic', 77, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 7, 'Hickory', 37, NULL, 'Deer Lakes', 46, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Second Round', 2, 8, 'Obama Academy of International Studies', 70, NULL, 'Cathedral Prep', 69, NULL, '2026-03-10');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Quarterfinals', 3, 1, 'Bishop McDevitt', 58, NULL, 'Lewisburg', 60, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Quarterfinals', 3, 2, 'Devon Prep', 62, NULL, 'Salisbury Township', 55, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Quarterfinals', 3, 3, 'Carver High School of Engineering & Science', 68, NULL, 'North Catholic', 61, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Quarterfinals', 3, 4, 'Deer Lakes', 41, NULL, 'Obama Academy of International Studies', 53, NULL, '2026-03-13');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Semi-Finals', 4, 1, 'Lewisburg', 49, NULL, 'Devon Prep', 73, NULL, '2026-03-16');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Semi-Finals', 4, 2, 'Carver High School of Engineering & Science', 51, NULL, 'Obama Academy of International Studies', 52, NULL, '2026-03-16');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_4a' LIMIT 1), 'Finals', 5, 1, 'Devon Prep', 58, NULL, 'Obama Academy of International Studies', 41, NULL, '2026-03-19');

-- Bracket 5: 2026 PIAA Boys Basketball Championships - 3A
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification) VALUES ('basketball', 76, '2026 PIAA Boys Basketball Championships - 3A', 'piaa_3a', '3A');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 1, 'West Catholic', 72, NULL, 'Lancaster Catholic', 47, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 2, 'Southern Columbia Area', 56, NULL, 'Executive Education Academy Charter School', 61, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 3, 'MAST Community Charter', 53, NULL, 'High School of the Future', 59, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 4, 'Riverside', 74, NULL, 'Mifflinburg', 50, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 5, 'Notre Dame-Green Pond', 59, NULL, 'TECH Freire Charter', 20, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 6, 'Lancaster Mennonite', 34, NULL, 'Lansdale Catholic', 30, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 7, 'Audenried', 68, NULL, 'Catasauqua', 62, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 8, 'Warrior Run', 72, NULL, 'Dunmore', 54, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 9, 'Trinity', 78, NULL, 'River Valley', 42, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 10, 'Everett', 38, NULL, 'Mohawk Area', 57, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 11, 'Forest Hills', 58, NULL, 'Shady Side Academy', 39, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 12, 'Aliquippa', 87, NULL, 'Cranberry Area', 52, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 13, 'Bishop Guilfoyle', 62, NULL, 'Ligonier Valley', 43, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 14, 'South Park', 90, NULL, 'Perry Traditional Academy', 61, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 15, 'South Allegheny', 51, NULL, 'Westmont Hilltop', 58, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'First Round', 1, 16, 'Eisenhower', 65, NULL, 'Seton LaSalle', 67, NULL, '2026-03-07');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 1, 'West Catholic', 52, NULL, 'Executive Education Academy Charter School', 49, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 2, 'High School of the Future', 51, NULL, 'Riverside', 58, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 3, 'Notre Dame-Green Pond', 66, NULL, 'Lancaster Mennonite', 61, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 4, 'Audenried', 59, NULL, 'Warrior Run', 64, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 5, 'Trinity', 69, NULL, 'Mohawk Area', 50, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 6, 'Forest Hills', 63, NULL, 'Aliquippa', 55, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 7, 'Bishop Guilfoyle', 65, NULL, 'South Park', 32, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Second Round', 2, 8, 'Westmont Hilltop', 46, NULL, 'Seton LaSalle', 35, NULL, '2026-03-11');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Quarterfinals', 3, 1, 'West Catholic', 58, NULL, 'Riverside', 50, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Quarterfinals', 3, 2, 'Notre Dame-Green Pond', 63, NULL, 'Warrior Run', 60, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Quarterfinals', 3, 3, 'Trinity', 75, NULL, 'Forest Hills', 53, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Quarterfinals', 3, 4, 'Bishop Guilfoyle', 50, NULL, 'Westmont Hilltop', 46, NULL, '2026-03-14');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Semi-Finals', 4, 1, 'West Catholic', 76, NULL, 'Notre Dame-Green Pond', 52, NULL, '2026-03-17');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Semi-Finals', 4, 2, 'Trinity', 50, NULL, 'Bishop Guilfoyle', 37, NULL, '2026-03-17');

INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_3a' LIMIT 1), 'Finals', 5, 1, 'West Catholic', 49, NULL, 'Trinity', 52, NULL, '2026-03-21');

COMMIT;
