-- Insert remaining playoff brackets: PIAA 2A, PIAA 1A, PCL
-- Season ID: 76, Sport: basketball
-- DO NOT touch existing brackets
BEGIN;

-- ============================================
-- Bracket: 2026 PIAA 2A Boys Basketball Championship
-- ============================================
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification)
VALUES ('basketball', 76, '2026 PIAA Boys Basketball Championships - 2A', 'piaa_2a', '2A');

-- First Round (March 7, 2026) - 16 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 1, 'Church Farm', 33, NULL, 'Constitution', 38, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 2, 'Schuylkill Haven', 46, NULL, 'Delone Catholic', 77, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 3, 'East Juniata', 37, NULL, 'Old Forge', 79, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 4, 'Vaux', 34, NULL, 'Delaware County Christian', 70, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 5, 'Northeast Bradford', 41, NULL, 'Susquehanna', 55, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 6, 'York Catholic', 50, NULL, 'Paul Robeson', 56, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 7, 'Neshannock', 36, NULL, 'United Valley', 54, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 8, 'Muncy', 42, NULL, 'Clarion Area', 46, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 9, 'Saegertown', 25, NULL, 'Sewickley Academy', 65, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 10, 'Bishop McCort', 64, NULL, 'Port Allegany', 67, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 11, 'Eden Christian', 55, NULL, 'McConnellsburg', 57, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 12, 'Clairton', 55, NULL, 'Cochranton', 52, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 13, 'Redbank Valley', 26, NULL, 'Jefferson-Morgan', 50, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 14, 'Northern Cambria', 34, NULL, 'Jeannette', 72, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 15, 'Conemaugh Township', 35, NULL, 'Our Lady of the Sacred Heart', 47, NULL, '2026-03-07');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'First Round', 1, 16, 'Winchester Thurston', 45, NULL, 'Mercyhurst Prep', 66, NULL, '2026-03-07');

-- Second Round (March 11, 2026) - 8 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 1, 'Delone Catholic', 49, NULL, 'Constitution', 47, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 2, 'Delaware County Christian', 53, NULL, 'Old Forge', 62, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 3, 'Paul Robeson', 77, NULL, 'Susquehanna', 40, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 4, 'Clarion Area', 39, NULL, 'United Valley', 53, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 5, 'Port Allegany', 29, NULL, 'Sewickley Academy', 76, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 6, 'Clairton', 30, NULL, 'McConnellsburg', 61, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 7, 'Jefferson-Morgan', 36, NULL, 'Jeannette', 68, NULL, '2026-03-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Second Round', 2, 8, 'Our Lady of the Sacred Heart', 45, NULL, 'Mercyhurst Prep', 46, NULL, '2026-03-11');

-- Quarterfinals (March 14, 2026) - 4 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Quarterfinals', 3, 1, 'Old Forge', 51, NULL, 'Delone Catholic', 39, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Quarterfinals', 3, 2, 'United Valley', 71, NULL, 'Paul Robeson', 61, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Quarterfinals', 3, 3, 'Sewickley Academy', 49, NULL, 'McConnellsburg', 38, NULL, '2026-03-14');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Quarterfinals', 3, 4, 'Mercyhurst Prep', 59, NULL, 'Jeannette', 58, NULL, '2026-03-14');

-- Semifinals (March 17, 2026) - 2 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Semifinals', 4, 1, 'United Valley', 48, NULL, 'Old Forge', 64, NULL, '2026-03-17');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Semifinals', 4, 2, 'Mercyhurst Prep', 39, NULL, 'Sewickley Academy', 64, NULL, '2026-03-17');

-- Championship (March 19, 2026) - 1 game
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_2a' LIMIT 1), 'Championship', 5, 1, 'Sewickley Academy', 52, NULL, 'Old Forge', 36, NULL, '2026-03-19');


-- ============================================
-- Bracket: 2026 PIAA 1A Boys Basketball Championship
-- ============================================
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification)
VALUES ('basketball', 76, '2026 PIAA Boys Basketball Championships - 1A', 'piaa_1a', '1A');

-- First Round (March 6, 2026) - 16 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 1, 'Lincoln Leadership Academy', 27, NULL, 'High Point Baptist Academy', 41, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 2, 'MaST Community Charter III', 45, NULL, 'West-Mont Christian Academy', 57, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 3, 'Weatherly', 45, NULL, 'Plumstead Christian', 60, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 4, 'Sullivan County', 48, NULL, 'Coventry Christian', 58, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 5, 'Our Lady of Lourdes Regional', 56, NULL, 'Bethlehem Christian', 86, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 6, 'Dayspring Christian Academy', 43, NULL, 'Sankofa Freedom Academy', 57, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 7, 'North Penn-Liberty', 41, NULL, 'York Country Day', 68, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 8, 'LaAcademia Partnership Charter', 49, NULL, 'Chester Charter Scholar Academy', 53, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 9, 'Conemaugh Valley', 59, NULL, 'Conestoga Christian', 76, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 10, 'Turkeyfoot Valley Area', 51, NULL, 'North Clarion', 53, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 11, 'West Middlesex', 35, NULL, 'Johnsonburg', 48, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 12, 'Saint Joseph''s Catholic Academy', 32, NULL, 'Neighborhood Academy', 50, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 13, 'Monessen', 29, NULL, 'Elk County Catholic', 61, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 14, 'Bishop Carroll', 49, NULL, 'Serra Catholic', 68, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 15, 'Cameron County', 50, NULL, 'Forbes Road', 58, NULL, '2026-03-06');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'First Round', 1, 16, 'Nazareth Prep', 74, NULL, 'Erie First Christian Academy', 92, NULL, '2026-03-06');

-- Second Round (March 10, 2026) - 8 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 1, 'West-Mont Christian Academy', 24, NULL, 'High Point Baptist Academy', 62, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 2, 'Coventry Christian', 47, NULL, 'Plumstead Christian', 34, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 3, 'Sankofa Freedom Academy', 82, NULL, 'Bethlehem Christian', 74, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 4, 'Chester Charter Scholar Academy', 44, NULL, 'York Country Day', 51, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 5, 'North Clarion', 37, NULL, 'Conestoga Christian', 66, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 6, 'Neighborhood Academy', 59, NULL, 'Johnsonburg', 47, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 7, 'Serra Catholic', 48, NULL, 'Elk County Catholic', 68, NULL, '2026-03-10');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Second Round', 2, 8, 'Forbes Road', 58, NULL, 'Erie First Christian Academy', 75, NULL, '2026-03-10');

-- Quarterfinals (March 13, 2026) - 4 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Quarterfinals', 3, 1, 'Coventry Christian', 41, NULL, 'High Point Baptist Academy', 50, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Quarterfinals', 3, 2, 'York Country Day', 70, NULL, 'Sankofa Freedom Academy', 78, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Quarterfinals', 3, 3, 'Conestoga Christian', 41, NULL, 'Neighborhood Academy', 81, NULL, '2026-03-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Quarterfinals', 3, 4, 'Erie First Christian Academy', 43, NULL, 'Elk County Catholic', 58, NULL, '2026-03-13');

-- Semifinals (March 16, 2026) - 2 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Semifinals', 4, 1, 'Sankofa Freedom Academy', 70, NULL, 'High Point Baptist Academy', 49, NULL, '2026-03-16');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Semifinals', 4, 2, 'Elk County Catholic', 37, NULL, 'Neighborhood Academy', 46, NULL, '2026-03-16');

-- Championship (March 19, 2026) - 1 game
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='piaa_1a' LIMIT 1), 'Championship', 5, 1, 'Neighborhood Academy', 52, NULL, 'Sankofa Freedom Academy', 55, NULL, '2026-03-19');


-- ============================================
-- Bracket: 2026 PCL Boys Basketball Championship
-- ============================================
INSERT INTO playoff_brackets (sport_id, season_id, name, bracket_type, classification)
VALUES ('basketball', 76, '2026 PCL Boys Basketball Championship', 'pcl', NULL);

-- First Round (February 11, 2026) - 2 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'First Round', 1, 1, 'Archbishop Ryan', 61, 7, 'La Salle College HS', 44, 10, '2026-02-11');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'First Round', 1, 2, 'St. Joseph''s Prep', 39, 8, 'West Catholic', 41, 9, '2026-02-11');

-- Quarterfinals (February 13, 2026) - 4 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Quarterfinals', 2, 1, 'Archbishop Wood', 65, 1, 'West Catholic', 41, 9, '2026-02-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Quarterfinals', 2, 2, 'Bonner-Prendergast', 72, 2, 'Archbishop Ryan', 58, 7, '2026-02-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Quarterfinals', 2, 3, 'Father Judge', 54, 6, 'Roman Catholic', 45, 3, '2026-02-13');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Quarterfinals', 2, 4, 'Neumann-Goretti', 61, 4, 'Archbishop Carroll', 51, 5, '2026-02-13');

-- Semifinals (February 18, 2026) - 2 games
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Semifinals', 3, 1, 'Father Judge', 52, 6, 'Archbishop Wood', 46, 1, '2026-02-18');
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Semifinals', 3, 2, 'Neumann-Goretti', 64, 4, 'Bonner-Prendergast', 60, 2, '2026-02-18');

-- Championship (February 22, 2026) - 1 game
INSERT INTO playoff_bracket_games (bracket_id, round_name, round_number, game_number, team1_name, team1_score, team1_seed, team2_name, team2_score, team2_seed, game_date) VALUES ((SELECT id FROM playoff_brackets WHERE sport_id='basketball' AND season_id=76 AND bracket_type='pcl' LIMIT 1), 'Championship', 4, 1, 'Father Judge', 55, 6, 'Neumann-Goretti', 52, 4, '2026-02-22');

COMMIT;
